import os
import sys
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from db.operations import upsert_fraud_pattern_record  # noqa: E402


# Curated patterns for initial intelligence corpus.
# Sources are captured as references for judges and demo narrative.
BASE_PATTERNS = [
    {
        "scam_type": "Investment Fraud",
        "sub_type": "Fake Trading Group",
        "official_category": "Investment/Trading Fraud",
        "national_cases": 100000,
        "loss_crore": 4000,
        "severity": "CRITICAL",
        "trigger_phrases": [
            "guaranteed returns",
            "vip trading group",
            "double your money",
            "limited slots",
            "withdrawal fee",
        ],
        "red_flags": [
            "Unrealistic monthly returns",
            "Telegram/WhatsApp closed group pressure",
            "Initial fake profit screenshots",
            "New deposit required to unlock withdrawals",
        ],
        "example_messages": [
            "Join our VIP stock group and get guaranteed 30 percent monthly returns.",
            "Your profit is ready. Pay processing fee to withdraw now.",
        ],
        "modus_operandi": "Fraudsters build trust with fake profits, then block withdrawals after repeated deposits.",
        "source": "I4C + media summaries (2024)",
    },
    {
        "scam_type": "Digital Arrest",
        "sub_type": "Fake CBI/ED Officer",
        "official_category": "Impersonation Fraud",
        "national_cases": 63481,
        "loss_crore": 1616,
        "severity": "CRITICAL",
        "trigger_phrases": [
            "digital arrest",
            "arrest warrant",
            "money laundering case",
            "stay on video call",
            "safe account transfer",
        ],
        "red_flags": [
            "Threat of immediate arrest",
            "Long coercive video call",
            "Demand for transfer to government safe account",
        ],
        "example_messages": [
            "This is cyber crime branch. Your Aadhaar is linked to money laundering.",
            "You are under digital arrest. Do not disconnect the call.",
        ],
        "modus_operandi": "Impersonation and fear are used to force urgent transfers under false legal threats.",
        "source": "I4C + state police advisories",
    },
    {
        "scam_type": "UPI Fraud",
        "sub_type": "Collect Request Scam",
        "official_category": "UPI/Payment Fraud",
        "national_cases": 632000,
        "loss_crore": 2800,
        "severity": "HIGH",
        "trigger_phrases": [
            "accept request to receive",
            "scan qr to get money",
            "olx buyer",
            "1 rupee verification",
        ],
        "red_flags": [
            "Collect request disguised as credit",
            "Fake buyer urgency",
            "Repeated insistence on QR/UPI approval",
        ],
        "example_messages": [
            "Please accept this UPI request to receive your payment.",
            "Scan this QR to collect your refund instantly.",
        ],
        "modus_operandi": "Victim approves a debit collect request while believing money is incoming.",
        "source": "NPCI fraud trends + police alerts",
    },
    {
        "scam_type": "KYC Fraud",
        "sub_type": "Bank KYC Update",
        "official_category": "Identity Theft",
        "severity": "CRITICAL",
        "trigger_phrases": [
            "kyc update",
            "account blocked",
            "verify aadhaar",
            "update pan",
            "bank compliance",
        ],
        "red_flags": [
            "Threatened account suspension",
            "Link to non-bank domain",
            "Request for OTP and account credentials",
        ],
        "example_messages": [
            "Your bank account will be blocked today. Complete KYC now.",
            "Update Aadhaar-PAN link via this urgent link.",
        ],
        "modus_operandi": "Victim enters credentials on phishing page and account is drained.",
        "source": "State cyber bulletins",
    },
    {
        "scam_type": "Part-Time Job Scam",
        "sub_type": "Task/Rating Scam",
        "official_category": "Job/Employment Fraud",
        "severity": "HIGH",
        "trigger_phrases": [
            "work from home",
            "like and earn",
            "hotel rating task",
            "prepaid task",
            "daily income",
        ],
        "red_flags": [
            "Easy money promise",
            "Small initial payout to build trust",
            "Deposit required to unlock commissions",
        ],
        "example_messages": [
            "Like videos and earn 5000 per day from home.",
            "Complete prepaid tasks to release your commission.",
        ],
        "modus_operandi": "Scammer lures victims with micro-tasks, then extracts repeated deposits.",
        "source": "NCRP trend analysis",
    },
    {
        "scam_type": "Lottery/Prize Fraud",
        "sub_type": "KBC Lucky Draw",
        "official_category": "Lottery/Prize Fraud",
        "severity": "HIGH",
        "trigger_phrases": [
            "you have won",
            "kbc lucky draw",
            "claim within 2 hours",
            "processing fee",
            "otp to verify prize",
        ],
        "red_flags": [
            "Unsolicited prize claim",
            "Urgent expiry window",
            "Request for sensitive data to release prize",
        ],
        "example_messages": [
            "Congratulations! You won 5 lakh in KBC lucky draw. Submit OTP now.",
            "Claim your government lottery reward before deadline.",
        ],
        "modus_operandi": "Fraudsters use fake winnings to harvest money and banking credentials.",
        "source": "NCRP + cyber advisory compilations",
    },
    {
        "scam_type": "Sextortion",
        "sub_type": "Recorded Video Call Blackmail",
        "official_category": "Sextortion/Blackmail",
        "severity": "CRITICAL",
        "trigger_phrases": [
            "i recorded your video",
            "pay or i send to family",
            "viral video",
            "urgent payment",
        ],
        "red_flags": [
            "Immediate blackmail demand",
            "Threat to expose private content",
            "Repeated extortion after payment",
        ],
        "example_messages": [
            "Pay 50,000 now or your video goes to all contacts.",
            "We will post your recording publicly if unpaid.",
        ],
        "modus_operandi": "Extortion follows a manipulated explicit call recording.",
        "source": "Police cyber extortion advisories",
    },
    {
        "scam_type": "Fake Customer Care",
        "sub_type": "Refund/Bank Support Impersonation",
        "official_category": "Customer Care Fraud",
        "severity": "CRITICAL",
        "trigger_phrases": [
            "refund processing",
            "share otp for verification",
            "install anydesk",
            "suspicious activity on your account",
        ],
        "red_flags": [
            "Impersonation of known brands",
            "Remote access app request",
            "OTP demand under pretext of security",
        ],
        "example_messages": [
            "This is bank support. Share OTP to secure your account.",
            "Install AnyDesk for instant refund assistance.",
        ],
        "modus_operandi": "Attackers impersonate support teams to gain device or account control.",
        "source": "Banking fraud advisories",
    },
    {
        "scam_type": "Loan App Fraud",
        "sub_type": "Predatory Instant Loan",
        "official_category": "Loan App Fraud",
        "severity": "HIGH",
        "trigger_phrases": [
            "instant loan",
            "no cibil",
            "approval in 5 minutes",
            "download app now",
        ],
        "red_flags": [
            "Excessive permissions",
            "Harassment for repayment",
            "Contact list misuse",
        ],
        "example_messages": [
            "Get instant loan with no documents. Install app now.",
            "Pre-approved loan offer for you today only.",
        ],
        "modus_operandi": "Apps abuse phone data and extort through harassment after disbursal.",
        "source": "RBI + state cyber warnings",
    },
    {
        "scam_type": "Matrimonial Fraud",
        "sub_type": "Fake NRI Profile",
        "official_category": "Matrimonial/Romance Fraud",
        "severity": "HIGH",
        "trigger_phrases": [
            "nri profile",
            "customs duty",
            "gift stuck at airport",
            "medical emergency transfer",
        ],
        "red_flags": [
            "Fast emotional trust building",
            "Move off platform to private chat",
            "Repeated emergency money requests",
        ],
        "example_messages": [
            "I sent a gift from abroad; pay customs fee to release it.",
            "Emergency surgery needed, please transfer urgently.",
        ],
        "modus_operandi": "Long-con emotional manipulation culminating in emergency transfer requests.",
        "source": "NCRP romance fraud trends",
    },
]


EXTRA_SCENARIOS = [
    (
        "Courier Scam",
        "Fake Parcel Customs Hold",
        "Impersonation Fraud",
        "HIGH",
        ["parcel held", "customs fee", "delivery suspended", "tracking issue"],
        ["Unexpected parcel charge", "Urgent payment request", "Unknown payment link"],
        ["Your parcel is held at customs. Pay fee now to avoid return."],
        "Scammers impersonate courier support and collect fake customs or redelivery payments.",
        "Courier fraud advisories",
    ),
    (
        "Electricity Bill Scam",
        "Power Disconnection Threat",
        "Utility Impersonation",
        "HIGH",
        ["electricity disconnected", "pay immediately", "late bill penalty", "lineman visit"],
        ["Threat of immediate disconnection", "UPI request from personal number", "Fake utility app"],
        ["Your electricity will be disconnected in 30 minutes. Pay on this number now."],
        "Fraudsters pose as utility board staff to force urgent bill payments.",
        "State utility cyber alerts",
    ),
    (
        "UPI Refund Scam",
        "QR Receive Fraud",
        "UPI/Payment Fraud",
        "HIGH",
        ["scan qr for refund", "receive money", "verification payment", "refund pending"],
        ["QR claimed as credit", "Collect request disguised as refund", "Pressure to act quickly"],
        ["Scan this QR to receive your refund instantly."],
        "Victim authorizes debit believing it is a credit/refund transaction.",
        "NPCI awareness material",
    ),
    (
        "Social Media Impersonation",
        "Friend Emergency Transfer",
        "Impersonation Fraud",
        "HIGH",
        ["urgent transfer", "medical emergency", "new number", "help now"],
        ["Known contact with new account", "High emotional pressure", "Refusal to verify by call"],
        ["I lost my wallet, please transfer urgently to this UPI."],
        "Compromised/clone profiles request emergency transfers from contacts.",
        "Platform safety advisories",
    ),
    (
        "Credit Card Reward Scam",
        "Reward Points Redemption Link",
        "Phishing",
        "HIGH",
        ["reward points expire", "redeem now", "card blocked", "cvv needed"],
        ["Phishing URL", "Card detail collection", "Expiry urgency"],
        ["Redeem your reward points now or they will expire today."],
        "Victims are lured to fake banking portals and submit card credentials.",
        "Bank anti-phishing circulars",
    ),
    (
        "PAN/Aadhaar Scam",
        "PAN Suspension Notice",
        "Identity Theft",
        "HIGH",
        ["pan suspended", "aadhaar mismatch", "link immediately", "compliance alert"],
        ["Government impersonation", "Credential harvesting form", "OTP demand"],
        ["Your PAN will be deactivated. Verify immediately."],
        "Fake compliance notices steal identity details and OTPs.",
        "Tax compliance fraud warnings",
    ),
    (
        "Scholarship Scam",
        "Student Grant Processing Fee",
        "Education Fraud",
        "MEDIUM",
        ["scholarship approved", "processing fee", "seat confirmation", "grant release"],
        ["Upfront payment for grant", "Unofficial domain", "No institutional verification"],
        ["Your scholarship has been approved. Pay processing to release amount."],
        "Students are targeted with fake financial aid disbursal messages.",
        "Education cyber advisories",
    ),
    (
        "Tour Package Scam",
        "Holiday Offer Deposit",
        "Travel Fraud",
        "MEDIUM",
        ["limited holiday offer", "book now", "token advance", "visa guaranteed"],
        ["Too-good-to-be-true pricing", "Advance-only payment", "No GST/agency verification"],
        ["Pay token amount now to lock your international package."],
        "Fake travel operators collect booking deposits and disappear.",
        "Travel fraud reports",
    ),
    (
        "Rental Scam",
        "Deposit Before Visit",
        "Marketplace Fraud",
        "MEDIUM",
        ["flat available", "token payment", "owner abroad", "no broker"],
        ["Advance payment before site visit", "Identity mismatch", "Pressure from fake demand"],
        ["Pay small token now, flat will be blocked for you."],
        "Fake property listings demand deposits before verification.",
        "Marketplace safety notices",
    ),
    (
        "Used Car Scam",
        "Army Seller Escrow Fraud",
        "Marketplace Fraud",
        "HIGH",
        ["army officer seller", "transport charge", "refundable token", "escrow"],
        ["Impersonation of defense personnel", "Fake escrow documents", "Transport advance demand"],
        ["Send refundable transport amount to release vehicle from depot."],
        "Scammers exploit trust by impersonating defense personnel in listings.",
        "Marketplace crime advisories",
    ),
    (
        "Insurance Scam",
        "Policy Lapse Reactivation",
        "Impersonation Fraud",
        "MEDIUM",
        ["policy lapsed", "renew now", "final warning", "pay penalty"],
        ["Urgent lapse warning", "Unverified payment account", "No official branch follow-up"],
        ["Your policy is lapsed. Pay penalty now to reactivate."],
        "Fraud callers impersonate insurers to collect fake renewal charges.",
        "Insurance regulator alerts",
    ),
    (
        "Mutual Fund Scam",
        "Guaranteed SIP Bonus",
        "Investment/Trading Fraud",
        "HIGH",
        ["guaranteed nav gain", "bonus units", "pre-ipo access", "assured returns"],
        ["Unrealistic returns", "Unofficial advisor channel", "Deposit to personal account"],
        ["Invest now for guaranteed monthly NAV growth and bonus units."],
        "Fake advisors run pump-and-dump style investment traps.",
        "SEBI investor warnings",
    ),
    (
        "Crypto Scam",
        "Signal Group Leverage Trap",
        "Investment/Trading Fraud",
        "CRITICAL",
        ["crypto signal", "leverage profits", "api key", "liquidation recovery"],
        ["Telegram-only broker", "API key harvesting", "Repeated top-up demands"],
        ["Join premium crypto signal room for 20 percent daily gains."],
        "Victims are lured into manipulated trades and repeated deposits.",
        "Crypto fraud monitoring",
    ),
    (
        "Mule Account Recruitment",
        "Commission for Account Access",
        "Money Mule Fraud",
        "CRITICAL",
        ["easy commission", "bank account rental", "kyc verified account", "receive and transfer"],
        ["Illegal account usage", "Unclear source of funds", "Promise of risk-free commission"],
        ["Earn commission by receiving money and forwarding it instantly."],
        "Recruiters use citizens as money mules for laundering proceeds.",
        "Law enforcement advisories",
    ),
    (
        "Remote Access Scam",
        "AnyDesk Refund Fraud",
        "Tech Support Fraud",
        "CRITICAL",
        ["install anydesk", "screen share", "refund support", "device verification"],
        ["Remote access request", "Credential/OTP capture", "Unauthorized transfers"],
        ["Install AnyDesk and share code for your refund processing."],
        "Attackers gain full device control and initiate fraudulent payments.",
        "Bank and CERT advisories",
    ),
    (
        "SIM Swap Fraud",
        "SIM Upgrade KYC",
        "Identity Theft",
        "CRITICAL",
        ["sim blocked", "sim upgrade", "telecom verification", "port immediately"],
        ["Telecom impersonation", "OTP interception risk", "Abrupt network loss"],
        ["Complete SIM KYC now or your number will be blocked."],
        "Victim number is taken over to intercept OTPs and reset banking access.",
        "Telecom fraud advisories",
    ),
    (
        "FASTag Scam",
        "KYC Reactivation Link",
        "Phishing",
        "HIGH",
        ["fastag blocked", "minimum kyc", "recharge failed", "vehicle blacklisted"],
        ["Fake transport authority domain", "Small recharge lure", "UPI collect trap"],
        ["Your FASTag is blocked. Update KYC now to avoid toll penalty."],
        "Drivers are redirected to phishing pages or collect requests.",
        "NHAI warning bulletins",
    ),
    (
        "E-commerce Scam",
        "Order Cancellation Refund",
        "Marketplace Fraud",
        "MEDIUM",
        ["order cancelled", "instant refund", "bank verification", "wallet credit"],
        ["Fake support contact", "Refund pretext for credential theft", "Urgent verification"],
        ["Your order failed. Verify account to receive refund immediately."],
        "Fraudsters mimic e-commerce support and steal payment credentials.",
        "Platform abuse reports",
    ),
    (
        "Gaming Scam",
        "Top-Up Discount Fraud",
        "Payment Fraud",
        "MEDIUM",
        ["diamond topup", "discount coupon", "admin panel", "id upgrade"],
        ["Payment outside platform", "Account takeover risk", "No official invoice"],
        ["Get 90 percent off top-up. Send payment to this UPI ID."],
        "Gamers are lured into off-platform payments and account theft.",
        "Gaming fraud alerts",
    ),
    (
        "Loan Closure Scam",
        "Foreclosure Settlement",
        "Impersonation Fraud",
        "HIGH",
        ["loan foreclosure", "one-time settlement", "noc issue", "processing charge"],
        ["Collection-agent impersonation", "Advance fee demand", "No branch confirmation"],
        ["Pay settlement processing amount now for immediate loan closure."],
        "Borrowers are tricked into fake closure payments.",
        "Consumer finance alerts",
    ),
    (
        "Charity Scam",
        "Disaster Relief Donation Fraud",
        "Donation Fraud",
        "MEDIUM",
        ["urgent donation", "flood relief", "child surgery", "instant transfer"],
        ["Unverified organization", "Emotional pressure", "No transparency"],
        ["Donate urgently to verified flood relief account."],
        "Fraud campaigns exploit crises for rapid donation collection.",
        "NGO fraud advisories",
    ),
    (
        "Employment Scam",
        "Airport Job Offer",
        "Job/Employment Fraud",
        "HIGH",
        ["airport hiring", "registration fee", "training deposit", "assured placement"],
        ["Paid interview process", "No official recruitment channel", "Document misuse"],
        ["Congratulations, pay registration to confirm airport job."],
        "Candidates are charged fake onboarding fees and lose identity data.",
        "Employment fraud watch",
    ),
    (
        "Visa Scam",
        "Express Visa Approval",
        "Travel Fraud",
        "HIGH",
        ["express visa", "embassy slot", "urgent processing", "guaranteed approval"],
        ["Fake embassy liaison", "Advance fee extraction", "Forged documents"],
        ["Pay expedited charges now for guaranteed visa approval."],
        "Victims are sold fake immigration processing services.",
        "Immigration fraud notices",
    ),
    (
        "ATM Card Scam",
        "Card Replacement OTP",
        "Phishing",
        "HIGH",
        ["card blocked", "replace card", "otp verification", "kiosk update"],
        ["OTP request from unknown caller", "Card details harvesting", "Urgency language"],
        ["Your card is blocked. Share OTP to activate replacement card."],
        "Impersonators harvest card and OTP data for account takeovers.",
        "Banking cybercrime notices",
    ),
    (
        "Tax Refund Scam",
        "Income Tax Refund Link",
        "Phishing",
        "HIGH",
        ["tax refund", "itr mismatch", "refund pending", "verify bank"],
        ["Government impersonation", "Credential phishing", "Deadline pressure"],
        ["Your income tax refund is pending. Verify details now."],
        "Fake tax portals steal credentials and OTPs.",
        "Income tax phishing alerts",
    ),
    (
        "UPI Autopay Scam",
        "Subscription Cancellation Trap",
        "UPI/Payment Fraud",
        "HIGH",
        ["autopay mandate", "cancel subscription", "verify upi", "collect request"],
        ["Mandate confusion", "Debit approval by victim", "Urgent cancellation pressure"],
        ["Approve this UPI request to cancel your subscription."],
        "Victims approve debit requests while trying to cancel subscriptions.",
        "Payment safety advisories",
    ),
    (
        "Investment App Fraud",
        "Clone Wealth App",
        "Investment/Trading Fraud",
        "CRITICAL",
        ["investment app", "guaranteed returns", "withdrawal blocked", "tax unlock"],
        ["Fake app dashboard", "Simulated gains", "Repeated deposit pressure"],
        ["Deposit more to unlock your profits and complete tax verification."],
        "Clone apps fabricate profits and block withdrawals.",
        "Cyber investment scam dossiers",
    ),
    (
        "QR Code Sticker Scam",
        "Merchant UPI Swap",
        "UPI/Payment Fraud",
        "HIGH",
        ["qr payment failed", "new qr", "merchant update", "cashback"],
        ["Tampered physical QR", "Funds diverted", "No merchant receipt"],
        ["Please scan this updated QR for payment."],
        "Fraudsters replace merchant QR codes with attacker UPI IDs.",
        "UPI fraud case studies",
    ),
    (
        "Screen-Recording Scam",
        "KYC Video Verification Abuse",
        "Identity Theft",
        "HIGH",
        ["video kyc", "face verification", "record screen", "share secure code"],
        ["Capture of sensitive on-screen data", "Social engineering via support pretext"],
        ["Start screen recording for your secure KYC update."],
        "Attackers harvest credentials shown during manipulated verification sessions.",
        "Digital identity safety alerts",
    ),
    (
        "Account Takeover",
        "Email OTP Reset Fraud",
        "Identity Theft",
        "CRITICAL",
        ["security reset", "otp required", "new device login", "suspicious sign-in"],
        ["Credential reset trick", "OTP relay", "Immediate lockout risk"],
        ["Share OTP to secure your account from suspicious login."],
        "Victims unknowingly authorize attacker password resets.",
        "Account security advisories",
    ),
    (
        "Courier Job Scam",
        "Delivery Partner Onboarding Fee",
        "Job/Employment Fraud",
        "MEDIUM",
        ["delivery job", "onboarding fee", "uniform charge", "fast joining"],
        ["Mandatory fee before interview", "No official HR verification"],
        ["Pay onboarding amount now to start courier job tomorrow."],
        "Job seekers are charged fake onboarding/kit fees.",
        "Gig-job fraud warnings",
    ),
    (
        "Scholarship Verification Scam",
        "Education Board OTP Fraud",
        "Education Fraud",
        "MEDIUM",
        ["education board", "document verify", "otp required", "scholarship disbursal"],
        ["Authority impersonation", "OTP phishing", "Urgent document pressure"],
        ["Share OTP to verify scholarship disbursal account."],
        "Fraud agents impersonate education boards to steal account access.",
        "Student safety advisories",
    ),
    (
        "Crypto Recovery Scam",
        "Wallet Recovery Fee",
        "Investment/Trading Fraud",
        "HIGH",
        ["recover losses", "blockchain tracing", "processing fee", "wallet unlock"],
        ["Second-order fraud targeting victims", "No verifiable credentials"],
        ["Pay tracing fee to recover your lost crypto assets."],
        "Victims of prior scams are re-targeted by fake recovery agencies.",
        "Post-fraud victim advisories",
    ),
    (
        "Pension Scam",
        "Pension Update OTP",
        "Identity Theft",
        "HIGH",
        ["pension blocked", "life certificate update", "otp verify", "bank change"],
        ["Senior citizen targeting", "Authority impersonation", "Urgent compliance tone"],
        ["Update life certificate now to avoid pension block."],
        "Fraudsters target pensioners for credential and OTP theft.",
        "Senior citizen cyber alerts",
    ),
    (
        "Healthcare Scam",
        "Insurance Claim Release",
        "Impersonation Fraud",
        "MEDIUM",
        ["claim approved", "hospital settlement", "processing charge", "otp confirm"],
        ["Fake TPA contact", "Advance fee demand", "Sensitive data request"],
        ["Pay claim processing charge to release settlement amount."],
        "Victims are tricked via fake health-claim disbursal calls.",
        "Healthcare claim fraud circulars",
    ),
    (
        "Demat Scam",
        "KYC Freeze Alert",
        "Investment Fraud",
        "HIGH",
        ["demat freeze", "kyc expired", "trade blocked", "reactivate now"],
        ["Broker impersonation", "Credential phishing", "Urgent market-close pressure"],
        ["Your demat is frozen. Verify now to continue trading."],
        "Investors are led to fake brokerage portals for credential theft.",
        "Brokerage cyber advisories",
    ),
    (
        "UPI Intent Scam",
        "Collect Intent Deep Link",
        "UPI/Payment Fraud",
        "HIGH",
        ["tap to receive", "intent link", "upi verification", "secure transfer"],
        ["Malicious deep link", "Auto-open collect flow", "Victim confusion"],
        ["Tap this secure UPI link to receive payment."],
        "Malicious intent links trigger hidden debit authorization flows.",
        "Mobile payment threat intel",
    ),
    (
        "Exam Scam",
        "Paper Leak Advance",
        "Education Fraud",
        "MEDIUM",
        ["paper leak", "guaranteed pass", "advance fee", "confidential set"],
        ["Illegal offer", "Advance payment only", "No verifiable source"],
        ["Pay now for guaranteed leaked question paper."],
        "Students are conned through fake exam leak and result manipulation offers.",
        "Exam fraud notices",
    ),
    (
        "Delivery App Scam",
        "Rider Verification Link",
        "Phishing",
        "MEDIUM",
        ["delivery failed", "rider verify", "reschedule", "otp required"],
        ["Fake tracking portal", "Credential/OTP collection", "Time pressure"],
        ["Verify rider details now to receive your order."],
        "Users submit data on fake delivery pages built for credential theft.",
        "E-commerce platform advisories",
    ),
    (
        "Matrimonial Blackmail",
        "Video Call Extortion",
        "Sextortion/Blackmail",
        "CRITICAL",
        ["video recording", "send to contacts", "pay now", "viral"],
        ["Immediate blackmail", "Repeat payment cycle", "Psychological intimidation"],
        ["Pay now or your video will be shared publicly."],
        "Attackers lure victims to explicit calls, record sessions, then extort money.",
        "Cyber extortion complaints",
    ),
    (
        "Government Subsidy Scam",
        "Scheme Enrollment Fee",
        "Impersonation Fraud",
        "MEDIUM",
        ["government scheme", "benefit release", "registration fee", "final approval"],
        ["Fake govt portal", "Fee demand for subsidy", "Aadhaar collection"],
        ["Pay registration to release your approved government benefit."],
        "Scammers misuse welfare scheme messaging to steal money and identity data.",
        "Public service fraud warnings",
    ),
    (
        "Bank Locker Scam",
        "Locker KYC Revalidation",
        "Impersonation Fraud",
        "HIGH",
        ["locker blocked", "kyc revalidation", "visit suspended", "unlock request"],
        ["Bank impersonation", "Remote verification demand", "OTP pretext"],
        ["Complete locker KYC to avoid permanent locker freeze."],
        "Locker customers are targeted through fake KYC verification calls.",
        "Bank customer advisories",
    ),
    (
        "Police Verification Scam",
        "E-FIR Settlement Demand",
        "Impersonation Fraud",
        "CRITICAL",
        ["police complaint", "settlement now", "warrant issued", "video verification"],
        ["Law enforcement impersonation", "Fear-based coercion", "Transfer demand"],
        ["A warrant is issued in your name. Settle immediately to avoid arrest."],
        "Imposters weaponize legal fear to force immediate transfers.",
        "Cyber police public notices",
    ),
    (
        "Ticket Booking Scam",
        "Tatkal Confirm Fee",
        "Travel Fraud",
        "MEDIUM",
        ["tatkal confirmed", "agent fee", "booking hold", "payment now"],
        ["Unofficial booking channel", "Advance payment", "No booking ID"],
        ["Pay extra now for guaranteed Tatkal confirmation."],
        "Fake agents exploit urgency around limited travel inventory.",
        "Travel fraud briefings",
    ),
    (
        "Wallet Upgrade Scam",
        "KYC Re-Activation Wallet",
        "Phishing",
        "HIGH",
        ["wallet blocked", "upgrade required", "kyc pending", "reactivate now"],
        ["Fake app/page", "Credential theft", "Urgent block warning"],
        ["Your wallet is blocked. Upgrade KYC to continue usage."],
        "Digital wallet users are redirected to phishing clones.",
        "Wallet provider advisories",
    ),
    (
        "Crowdfunding Scam",
        "Emergency Fundraiser Fraud",
        "Donation Fraud",
        "MEDIUM",
        ["urgent surgery", "donate now", "verified case", "last date"],
        ["No medical proof", "Pressure via social sharing", "Unverified beneficiary"],
        ["Urgent child surgery case, donate immediately to save life."],
        "Fraud campaigns mimic emergency fundraisers to collect donations.",
        "NGO due-diligence advisories",
    ),
    (
        "Business Invoice Scam",
        "Vendor Bank Change Email",
        "Business Email Compromise",
        "CRITICAL",
        ["updated bank account", "urgent invoice", "payment pending", "new beneficiary"],
        ["Unexpected account-change notice", "Email spoofing", "No phone verification"],
        ["Please process this invoice to our new bank account today."],
        "Spoofed vendor communications redirect legitimate business payments.",
        "BEC threat intelligence",
    ),
    (
        "Online Exam Proctor Scam",
        "Remote Access During Exam",
        "Education Fraud",
        "MEDIUM",
        ["proctor setup", "install plugin", "screen control", "identity check"],
        ["Unknown remote-control software", "Credential capture", "Device compromise"],
        ["Install this tool and share code for exam verification."],
        "Students are tricked into granting remote access under exam-prep pretext.",
        "Academic cyber bulletins",
    ),
    (
        "Hotel Booking Scam",
        "Advance Confirmation Fraud",
        "Travel Fraud",
        "MEDIUM",
        ["booking confirmed", "advance deposit", "weekend surge", "limited rooms"],
        ["Payment to personal UPI", "No GST invoice", "No official booking reference"],
        ["Transfer advance now to lock your discounted room."],
        "Fake booking desks collect deposits for non-existent reservations.",
        "Tourism fraud reports",
    ),
    (
        "Freelance Scam",
        "Portfolio Deposit Requirement",
        "Job/Employment Fraud",
        "MEDIUM",
        ["freelance project", "security deposit", "client escrow", "payment release"],
        ["Upfront payment for work", "No verified client identity", "Repeated fee requests"],
        ["Pay security deposit to start freelance assignment today."],
        "Freelancers are trapped with fake project onboarding deposits.",
        "Remote work fraud advisories",
    ),
    (
        "OTT Subscription Scam",
        "Account Suspension Alert",
        "Phishing",
        "MEDIUM",
        ["subscription expired", "account suspended", "update payment", "verify now"],
        ["Brand impersonation", "Card data collection", "Urgent service interruption warning"],
        ["Your streaming account is suspended. Update billing now."],
        "Users are phished via fake subscription-renewal portals.",
        "Consumer phishing advisories",
    ),
    (
        "Tax Penalty Scam",
        "Immediate Penalty Settlement",
        "Impersonation Fraud",
        "HIGH",
        ["penalty due", "legal action", "settle now", "final notice"],
        ["Legal threat language", "Payment to personal account", "No verified notice number"],
        ["Final tax penalty notice: pay now to avoid legal action."],
        "Scammers use fake tax notices to force panic payments.",
        "Revenue fraud bulletins",
    ),
    (
        "Prepaid Card Scam",
        "Gift Card Verification",
        "Payment Fraud",
        "MEDIUM",
        ["gift card code", "verification", "refund release", "activate credit"],
        ["Code sharing demand", "Irreversible value transfer", "No legitimate verification path"],
        ["Share gift card code to receive your refund."],
        "Attackers convert stolen value through gift-card harvesting.",
        "Consumer protection warnings",
    ),
    (
        "Network Marketing Scam",
        "Membership Unlock Fraud",
        "Investment/Trading Fraud",
        "MEDIUM",
        ["membership upgrade", "binary income", "downline bonus", "activation fee"],
        ["Recruitment pressure", "Unverifiable payout claims", "Constant fee top-ups"],
        ["Pay activation fee now to unlock passive monthly income."],
        "Victims are trapped into recurring fee-based pseudo-investment ladders.",
        "Consumer finance advisories",
    ),
]


def _scenario_to_pattern(item: tuple) -> dict:
    (
        scam_type,
        sub_type,
        official_category,
        severity,
        trigger_phrases,
        red_flags,
        example_messages,
        modus_operandi,
        source,
    ) = item
    return {
        "scam_type": scam_type,
        "sub_type": sub_type,
        "official_category": official_category,
        "severity": severity,
        "trigger_phrases": trigger_phrases,
        "red_flags": red_flags,
        "example_messages": example_messages,
        "modus_operandi": modus_operandi,
        "source": source,
    }


PATTERNS = BASE_PATTERNS + [_scenario_to_pattern(item) for item in EXTRA_SCENARIOS]


def seed() -> None:
    inserted = 0
    for item in PATTERNS:
        record = {
            **item,
            "year": 2024,
            "active": True,
            "version": "seed-2026-04",
            "created_at": datetime.now(timezone.utc).isoformat(),
        }
        ok = upsert_fraud_pattern_record(record)
        if ok:
            inserted += 1
            print(f"[OK] {record['scam_type']} :: {record['sub_type']}")
        else:
            print(f"[FAIL] {record['scam_type']} :: {record['sub_type']}")

    print("-")
    print(f"Inserted/updated: {inserted}/{len(PATTERNS)} patterns")


if __name__ == "__main__":
    seed()
